config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  namespace :admin do
    get '/' => 'home#index'
    resources :products do
      resources :tracks
    end
    resources :users do
      get 'products'
      get 'all_products'
      post 'assign_product'
      delete 'remove_product'
    end
  end

  apipie
  devise_for :users
	namespace :api do
		post 'login' => 'sessions#create'
    post 'register' => 'registrations#create'
    post 'forgot-password' => 'sessions#forgot_password'

    get 'products' => 'products#index'
    get 'tracks' => 'tracks#index'

    get 'track-detail' => 'tracks#show'
	end

end

app/models/track.rb
class Track < ApplicationRecord
  	belongs_to :product
  	validates :status, :track_type, :product_id, presence: true
  	enum track_type: [:heatup, :box, :kick, :power, :combat, :superbox, :interactive, :relaxing, :misc, :sequence, :free]
  	enum status: [:active, :archived, :unpublished]

    has_attached_file :file
    validates_attachment_content_type :file, content_type: ['audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio']

end

app/controllers/admin/tracks_controller.rb
class Admin::TracksController < Admin::AdminController

  before_action :set_product
  before_action :set_track, except: [:index, :new, :create]

  def new
    @track = Track.new
    @track.product = @product
    render '_form', layout: false
  end

  def create
    @track = Track.new track_params
    @track.product_id = @product.id
    if @track.save
      @success = true
      flash[:notice] = 'Se creó el track'
    else
      @success = false
      @errors = @track.errors.full_messages
    end
    respond_to do |format|
			format.html do
				redirect_to admin_product_tracks_path(@product)
			end
			format.js  { render 'admin/partials/_generic_js_response', layout: false }
		end
  end

  def edit
    render '_form', layout: false
  end

  def update
    if @track.update_attributes track_params
      flash[:notice] = 'Se actualizó el track'
      @success = true
    else
      @success = false
      @errors = @track.errors.full_messages
    end
    respond_to do |format|
			format.html do
				redirect_to admin_product_tracks_path(@product)
			end
			format.js  { render 'admin/partials/_generic_js_response', layout: false }
		end
  end

  def destroy
    if @track.destroy
      @success = true
      flash[:notice] = 'Se eliminó el track'
    else
      @success = false
      @errors = @track.errors.full_messages
    end
    render 'admin/partials/_generic_js_response', layout: false
  end

  private
  def track_params
    params.require(:track).permit!
  end

  def set_product
    @product = Product.find params[:product_id]
  end

  def set_track
    @track = Track.find params[:id]
  end
end

app/controllers/api/tracks_controller.rb
class Api::TracksController < ApiController

	before_action :check_session

	# List available tracks
	# Params:
	# current_user*
	# product_id
	# page
	# limit
	api :GET, '/tracks', "List all available products for requesting user"
	param :product_id, String, "The Product id", required: true
	def index
		response = Tracks::List.call({current_user: current_user, product_id: params[:product_id], limit: params[:limit], page: params[:page]})
        render json: {response: response[:response], status: response[:status]}
	end

	api :GET, '/track-detail', "Show specific track information"
	param :track_id, String, "The track id", required: true
	def show
		response = Tracks::Show.call({current_user: current_user, track_id: params[:track_id]})
        render json: {response: response[:response], status: response[:status]}
	end
end

app/views/admin/tracks/_form.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<%= form_for([:admin,@product,@track], {remote: true, multipart: true}) do |f| -%>
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 class="modal-title">Información del track</h3>
		</div>
		<div class="modal-body">
			<div class="alert alert-danger" style="display: none" id="record-errors"></div>
			<table class="table">
				<tr>
					<td><%= f.label :track_type, "Tipo" -%></td>
					<td><%= f.select :track_type, options_for_select(Track.track_types.map { |e| [e[0]] },@track.track_type),{include_blank: 'Selecciona un tipo'}, {required: true, class: 'form-control'} -%></td>
          <td><%= f.label :video_url, "URL Video" -%></td>
          <td><%= f.text_field :video_url, required: true, class: 'form-control' -%></td>
				</tr>
        <tr>
					<td><%= f.label :file, "Archivo MP3/MP4 #{'- Sobreescribir?' if @track.file.present?}" -%></td>
					<td><%= f.file_field :file -%></td>
          <td></td>
          <td></td>
				</tr>
			</table>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
			<button type="submit" class="btn btn-sm btn-primary">Guardar</button>
		</div>
		<% end -%>
	</div>
</div>

app/views/admin/tracks/index.html.erb
<div class="content-header">
	<div class="header-section">
		<h1>
			<i class="fa fa-music"></i><b>Producto <%= @product.name -%></b><br><small>Visualice los detalles del producto</small>
		</h1>
    <a href="javascript:void(0)" onclick="load_new_track_form()" class="btn btn-primary">Crear Track</a>

		<% if flash[:notice] -%>
			<div class="alert alert-success"><%= flash[:notice] -%></div>
		<% end -%>
	</div>
</div>
<ul class="breadcrumb breadcrumb-top">
	<li><a href="/admin">Inicio</a></li>
	<li><a href="<%= admin_products_path -%>">Productos</a></li>
	<li><a href="<%= admin_product_path(@product) -%>">Producto <%= @product.name -%></a></li>
  <li><a href="<%= admin_product_tracks_path(@product) -%>">Tracks</a></li>
</ul>

<div class="block full block-alt-noborder">
	<ul class="nav nav-tabs">
    <li class="<%= 'active' if action_name == 'show' and controller_name == 'products' -%>"><a href="<%= admin_product_path(@product) -%>">Detalles</a></li>
		<li class="<%= 'active' if action_name == 'index' and controller_name == 'tracks' -%>"><a href="<%= admin_product_tracks_path(@product) -%>">Tracks</a></li>
	</ul>
	<div class="tab-content">
		<br>
		<div class="row">
      <div class="col-md-12">
        <table class="table data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Tipo</th>
              <th>Duración</th>
              <th>URL Track</th>
              <th>URL Video</th>
              <th class="text-right">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @product.tracks.each do |track| %>
            <tr>
              <td><%= track.id %></td>
              <td><%= track.track_type %></td>
              <td><%= track.duration %></td>
              <td><%= link_to track.file_file_name, track.file.url, target: '_blank' if track.file.present? %></td>
              <td><%= link_to track.video_url, track.video_url, target: '_blank' if track.video_url.present? %></td>
              <td class="text-right">
                <div class="btn-group">
    							<a href="javascript:void(0)" data-toggle="dropdown" class="btn btn-xs btn-primary dropdown-toggle" aria-expanded="false">Acciones <span class="caret"></span></a>
    							<ul class="dropdown-menu text-left">
                    <li><%= link_to "Editar", '#', onclick: "load_modal(#{track.id},'edit_track')" %></li>
                    <li><%= link_to "Eliminar", admin_product_track_path(@product,track), data:{remote: true, method: :delete, confirm: 'Está seguro que desea eliminar este track?'} %></li>
                  </ul>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
		</div>
	</div>
</div>


<div id="row-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">

</div>

<% content_for :footer_scripts do  -%>

	<script type="text/javascript">

    function load_new_track_form(){
			$.get("<%= new_admin_product_track_path(@product) -%>", function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
		}

    function load_edit_product_form(){
      $.get("<%= edit_admin_product_path(@product) -%>", function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
    }

    function load_modal(record_id,action){
      url = ""
      switch (action) {
				case 'edit_track':
					url = "<%= edit_admin_product_track_path(@product,1) %>"
					break;
        default:
          alert('unknown action ' + action)
      }
			$.get(url.replace(/\/1\b(?!.*?\/1\b)/, '/'+ record_id), {id: record_id}, function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
		}

	</script>
<% end -%>