config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  namespace :admin do
    get '/' => 'home#index'
    resources :products do
      resources :tracks
    end
    resources :users do
      get 'products'
      get 'all_products'
      post 'assign_product'
      delete 'remove_product'
    end
  end

  apipie
  devise_for :users
	namespace :api do
		post 'login' => 'sessions#create'
    post 'register' => 'registrations#create'
    post 'forgot-password' => 'sessions#forgot_password'

    get 'products' => 'products#index'
    get 'tracks' => 'tracks#index'

    get 'track-detail' => 'tracks#show'
	end

end

app/models/product.rb
class Product < ApplicationRecord

	has_many :tracks
	validates :name, :status, presence: true

	enum status: [:active, :archived, :unpublished]
	#enum product_type: [:free, :structured]

	has_many :user_products
	has_many :users, through: :user_products

  has_attached_file :guide
  validates_attachment_content_type :guide, content_type: ['application/pdf']

	# Renders a version of the cover_url according to the screen size
	def cover_url(screen_size=nil)
		# TODO: Implement
		"https://www.abc.es/media/play/2017/09/28/avatar-kVmB--620x349@abc.jpeg"
	end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController

  before_action :set_product, except: [:index, :new, :create]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    render '_form', layout: false
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:notice] = 'Se creó el producto'
			@success = true
    else
      @success = false
      @errors = @product.errors.full_messages
      flash[:notice] = @errors
    end

    respond_to do |format|
			format.html do
				redirect_to admin_products_path
			end
			format.js  { render 'admin/partials/_generic_js_response', layout: false }
		end
  end

  def edit
    render '_form', layout: false
  end

  def update
    if @product.update_attributes product_params
      @success = true
      flash[:notice] = 'Se actualizó el producto'
    else
      @success = false
      @errors = @product.errors.full_messages
    end
    respond_to do |format|
			format.html do
				redirect_to admin_product_path(@product)
			end
			format.js  { render 'admin/partials/_generic_js_response', layout: false }
		end
  end

  def destroy
    @success = true
    render 'admin/partials/_generic_js_response', layout: false
  end

  private
  def set_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit!
  end

end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApiController

	before_action :check_session

	# List available products
	# Params:
	# current_user*
	# page
	# limit
	api :GET, '/products', "List all available products for requesting user"
	def index
		response = Products::List.call({current_user: current_user, limit: params[:limit], page: params[:page]})
        render json: {response: response[:response], status: response[:status]}
	end
end

app/views/admin/products/_form.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<%= form_for([:admin,@product], remote: true, multipart: true) do |f| -%>
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 class="modal-title">Información del producto</h3>
		</div>
		<div class="modal-body">

				<div class="alert alert-danger" style="display: none" id="record-errors"></div>

				<table class="table">
					<tr>
						<td><%= f.label :name, "Nombre" -%></td>
						<td><%= f.text_field :name, required: true, class: 'form-control', placeholder: 'Ingrese el nombre del producto' -%></td>
						<td><%= f.label :status, "Estado" -%></td>
						<td><%= f.select :status, options_for_select(Product.statuses.map { |e| [e[0]] },@product.status),{include_blank: 'Selecciona un estado'}, {required: true, class: 'form-control'} -%></td>
					</tr>
          <tr>
  					<td><%= f.label :guide, "Archivo de esquemas PDF #{'- Sobreescribir?' if @product.guide.present?}" -%></td>
  					<td><%= f.file_field :guide -%></td>
  				</tr>
				</table>

		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
			<button type="submit" class="btn btn-sm btn-primary">Guardar</button>
		</div>
		<% end -%>
	</div>
</div>

app/views/admin/products/index.html.erb
<div class="content-header">
	<div class="header-section">
		<h1>
			<i class="gi gi-building"></i>Productos<br><small>Acceda al listado de productos</small>
		</h1>
		<% if flash[:notice] -%>
		<div class="alert alert-success"><%= flash[:notice] -%></div>
		<% end -%>
		<button type="button" class="btn btn-success" onclick="load_entity_form()">Crear nuevo producto</button>
	</div>
</div>
<ul class="breadcrumb breadcrumb-top">
	<li><a href="/admin">Inicio</a></li>
	<li><a href="<%= admin_products_path -%>">Productos</a></li>
</ul>
<div class="block full block-alt-noborder table-responsive">
	<table class="table data-table">
		<thead>
			<tr>
        <th>ID</th>
				<th>Producto</th>
				<th>Fecha de creación</th>
				<th>Estado</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| -%>
			<tr>
        <td><%= product.id %></td>
				<td><%= product.name %></td>
        <td><%= product.created_at %></td>
        <td><%= product.status.capitalize %></td>
				<td>
          <%= link_to "Ingresar", admin_product_path(product), class: 'btn btn-xs btn-primary' %>
				</td>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>


<% content_for :footer_scripts do  -%>

<script type="text/javascript">

	function load_entity_form(){
		$.get("<%= new_admin_product_path -%>", function(view){
			$("#row-modal").html(view)
			$("#row-modal").modal('show')
		})
	}

</script>
<% end -%>


<div id="row-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">

</div>

app/views/admin/products/show.html.erb
<div class="content-header">
	<div class="header-section">
		<h1>
			<i class="fa fa-music"></i><b>Producto <%= @product.name -%></b><br><small>Visualice los detalles del producto</small>
		</h1>
		<a href="javascript:void(0)" onclick="load_edit_product_form()" class="btn btn-primary">Editar</a>

		<% if flash[:notice] -%>
			<div class="alert alert-success"><%= flash[:notice] -%></div>
		<% end -%>
	</div>
</div>
<ul class="breadcrumb breadcrumb-top">
	<li><a href="/admin">Inicio</a></li>
	<li><a href="<%= admin_products_path -%>">Productos</a></li>
	<li><a href="<%= admin_product_path(@product) -%>">Producto <%= @product.name -%></a></li>
</ul>

<div class="block full block-alt-noborder">
	<ul class="nav nav-tabs">
    <li class="<%= 'active' if action_name == 'show' and controller_name == 'products' -%>"><a href="<%= admin_product_path(@product) -%>">Detalles</a></li>
		<li class="<%= 'active' if action_name == 'index' and controller_name == 'tracks' -%>"><a href="<%= admin_product_tracks_path(@product) -%>">Tracks</a></li>
	</ul>
	<div class="tab-content">
		<br>
		<div class="row">
      <div class="col-md-12">
        <table class="table">
          <tr>
            <td width="200px"><b>Nombre del producto:</b></td>
            <td><%= @product.name %></td>
          </tr>
          <tr>
            <td width="200px"><b>Archivo de esquemas:</b></td>
            <td><%= link_to @product.guide_file_name, @product.guide.url, target: '_blank' if @product.guide.present? %></td>
          </tr>
          <tr>
            <td width="200px"><b>Estado:</b></td>
            <td><%= @product.status %></td>
          </tr>
          <tr>
            <td width="200px"><b>Fecha de creación:</b></td>
            <td><%= @product.created_at %></td>
          </tr>
        </table>
      </div>
		</div>
	</div>
</div>


<div id="row-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">

</div>

<% content_for :footer_scripts do  -%>

	<script type="text/javascript">

    function load_new_track_form(){
			$.get("<%= new_admin_product_track_path(@product) -%>", function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
		}

    function load_edit_product_form(){
      $.get("<%= edit_admin_product_path(@product) -%>", function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
    }

	</script>
<% end -%>