config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  namespace :admin do
    get '/' => 'home#index'
    resources :products do
      resources :tracks
    end
    resources :users do
      get 'products'
      get 'all_products'
      post 'assign_product'
      delete 'remove_product'
    end
  end

  apipie
  devise_for :users
	namespace :api do
		post 'login' => 'sessions#create'
    post 'register' => 'registrations#create'
    post 'forgot-password' => 'sessions#forgot_password'

    get 'products' => 'products#index'
    get 'tracks' => 'tracks#index'

    get 'track-detail' => 'tracks#show'
	end

end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :first_name, :last_name, :email, :role, :status, presence: true

	attr_accessor :request_info

	enum status: [:active, :archived]
	enum role: [:admin, :user]

	has_many :user_products
	has_many :products, through: :user_products

	def send_reset_password_instructions
		rescue "Implement me"
	end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    render '_form', layout: false
  end

  def create
    @user = User.new user_params
    @user.password, @user.password_confirmation = @user.email
    if @user.save
      @success = true
      flash[:notice] = 'Se creó el usuario exitosamente'
    else
      @success = false
      @errors = @user.errors.full_messages
    end
    render 'admin/partials/_generic_js_response', layout: false
  end

  def edit
    render '_form', layout: false
  end

  def update
    if @user.update_attributes user_params
      @success = true
      flash[:notice] = 'Se actualizó el usuario exitosamente'
    else
      @success = false
      @errors = @user.errors.full_messages
    end
    render 'admin/partials/_generic_js_response', layout: false
  end

  def destroy
    if @user.destroy
      @success = true
      flash[:notice] = 'Se eliminó el usuario exitosamente'
    else
      @success = false
      @errors = @user.errors.full_messages
    end
    render 'admin/partials/_generic_js_response', layout: false
  end

  def products
  end

  def all_products
    @products = Product.where(status: Product.statuses[:active])
    render '_all_products', layout: false
  end

  def assign_product
    up = UserProduct.new(user_id: @user.id, product_id: params[:user_product][:product_id])
    if up.save
      @success = true
      flash[:notice] = 'Se asignó el producto al usuario'
    else
      @success = false
      @errors = up.errors.full_messages
    end
    render 'admin/partials/_generic_js_response', layout: false
  end

  def remove_product
    UserProduct.where(user_id: @user.id, product_id: params[:product_id]).first.destroy
    @success = true
    flash[:notice] = 'Se eliminó el producto exitosamente'
    render 'admin/partials/_generic_js_response', layout: false
  end

  private
  def set_user
    if params[:user_id]
      @user = User.find params[:user_id]
    else
      @user = User.find params[:id]
    end
  end

  def user_params
    params.require(:user).permit!
  end
end

app/views/admin/users/_all_products.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<%= form_for(:user_product, url: admin_user_assign_product_path(@user), remote: true, multipart: true) do |f| -%>
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 class="modal-title">Asignar producto a usuario</h3>
		</div>
		<div class="modal-body">
				<div class="alert alert-danger" style="display: none" id="record-errors"></div>
				<table class="table">
					<tr>
						<td><%= f.label :product_id, "Estado" -%></td>
						<td><%= f.select :product_id, options_for_select(@products.map { |e| [e.name,e.id] }),{include_blank: 'Selecciona un producto de la lista'}, {required: true, class: 'form-control'} -%></td>
					</tr>
				</table>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
			<button type="submit" class="btn btn-sm btn-primary">Guardar</button>
		</div>
		<% end -%>
	</div>
</div>

app/views/admin/users/_form.html.erb
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<%= form_for([:admin,@user], remote: true, multipart: true) do |f| -%>
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 class="modal-title">Información del usuario</h3>
		</div>
		<div class="modal-body">

				<div class="alert alert-danger" style="display: none" id="record-errors"></div>

				<table class="table">
					<tr>
						<td><%= f.label :first_name, "Nombres" -%></td>
						<td><%= f.text_field :first_name, required: true, class: 'form-control', placeholder: 'Pedro' -%></td>
            <td><%= f.label :last_name, "Apellidos" -%></td>
						<td><%= f.text_field :last_name, required: true, class: 'form-control', placeholder: 'Perez' -%></td>
					</tr>
          <tr>
            <td><%= f.label :role, "Rol" -%></td>
						<td><%= f.select :role, options_for_select(User.roles.map { |e| [e[0]] },@user.role),{include_blank: 'Selecciona un rol'}, {required: true, class: 'form-control'} -%></td>
            <td><%= f.label :email, "Email" -%></td>
						<td><%= f.text_field :email, required: true, class: 'form-control', placeholder: 'pedro@perez.com' -%></td>
  				</tr>
				</table>

		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
			<button type="submit" class="btn btn-sm btn-primary">Guardar</button>
		</div>
		<% end -%>
	</div>
</div>

app/views/admin/users/index.html.erb
<div class="content-header">
	<div class="header-section">
		<h1>
			<i class="gi gi-building"></i>Usuarios<br><small>Acceda al listado de usuarios</small>
		</h1>
		<% if flash[:notice] -%>
		<div class="alert alert-success"><%= flash[:notice] -%></div>
		<% end -%>
		<button type="button" class="btn btn-success" onclick="load_entity_form()">Crear nuevo usuario</button>
	</div>
</div>
<ul class="breadcrumb breadcrumb-top">
	<li><a href="/admin">Inicio</a></li>
	<li><a href="<%= admin_users_path -%>">Usuarios</a></li>
</ul>
<div class="block full block-alt-noborder table-responsive">
	<table class="table data-table">
		<thead>
			<tr>
        <th>ID</th>
				<th>Nombre</th>
				<th>Rol</th>
        <th>Email</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| -%>
			<tr>
        <td><%= user.id %></td>
				<td><%= user.full_name %></td>
        <td><%= user.role %></td>
        <td><%= user.email %></td>
				<td>
          <%= link_to "Ingresar", admin_user_path(user), class: 'btn btn-xs btn-primary' %>
				</td>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>


<% content_for :footer_scripts do  -%>

<script type="text/javascript">

	function load_entity_form(){
		$.get("<%= new_admin_user_path -%>", function(view){
			$("#row-modal").html(view)
			$("#row-modal").modal('show')
		})
	}

</script>
<% end -%>


<div id="row-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">

</div>

app/views/admin/users/products.html.erb
<div class="content-header">
	<div class="header-section">
		<h1>
			<i class="fa fa-music"></i><b>Usuario <%= @user.full_name -%></b><br><small>Visualice las suscripciones de este usuario</small>
		</h1>
    <a href="javascript:void(0)" onclick="load_all_products_form()" class="btn btn-primary">Asignar Producto</a>

		<% if flash[:notice] -%>
			<div class="alert alert-success"><%= flash[:notice] -%></div>
		<% end -%>
	</div>
</div>
<ul class="breadcrumb breadcrumb-top">
	<li><a href="/admin">Inicio</a></li>
	<li><a href="<%= admin_users_path -%>">Usuarios</a></li>
	<li><a href="<%= admin_user_path(@user) -%>">Usuario <%= @user.full_name -%></a></li>
  <li><a href="<%= admin_user_products_path(@user) -%>">Productos</a></li>
</ul>

<div class="block full block-alt-noborder">
	<ul class="nav nav-tabs">
    <li class="<%= 'active' if action_name == 'show' -%>"><a href="<%= admin_user_path(@user) -%>">Detalles</a></li>
		<li class="<%= 'active' if action_name == 'products' -%>"><a href="<%= admin_user_products_path(@user) -%>">Suscripción de Productos</a></li>
	</ul>
	<div class="tab-content">
		<br>
		<div class="row">
      <div class="col-md-12">
        <table class="table data-table">
          <thead>
            <tr>
              <th width="200px">Producto</th>
              <th>Fecha de registro</th>
              <th class="text-right">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @user.user_products.each do |up| %>
            <tr>
              <td>Producto <%= up.product.name %></td>
              <td><%= up.created_at %></td>
              <td class="text-right">
                <%= link_to "Eliminar", admin_user_remove_product_path(@user,product_id: up.product_id), data:{remote: true, method: :delete, confirm: 'Está seguro que desea eliminar este producto de este usuario?'}, class: 'btn btn-primary btn-xs' %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
		</div>
	</div>
</div>


<div id="row-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">

</div>

<% content_for :footer_scripts do  -%>

	<script type="text/javascript">

    function load_all_products_form(){
			$.get("<%= admin_user_all_products_path(@user) -%>", function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
		}

	</script>
<% end -%>

app/views/admin/users/show.html.erb
<div class="content-header">
	<div class="header-section">
		<h1>
			<i class="fa fa-music"></i><b>Usuario <%= @user.full_name -%></b><br><small>Visualice los detalles del usuario</small>
		</h1>
		<a href="javascript:void(0)" onclick="load_edit_user_form()" class="btn btn-primary">Editar</a>

		<% if flash[:notice] -%>
			<div class="alert alert-success"><%= flash[:notice] -%></div>
		<% end -%>
	</div>
</div>
<ul class="breadcrumb breadcrumb-top">
	<li><a href="/admin">Inicio</a></li>
	<li><a href="<%= admin_users_path -%>">Usuarios</a></li>
	<li><a href="<%= admin_user_path(@user) -%>">Usuario <%= @user.full_name -%></a></li>
</ul>

<div class="block full block-alt-noborder">
	<ul class="nav nav-tabs">
    <li class="<%= 'active' if action_name == 'show' -%>"><a href="<%= admin_user_path(@user) -%>">Detalles</a></li>
		<li class="<%= 'active' if action_name == 'products' -%>"><a href="<%= admin_user_products_path(@user) -%>">Suscripción de Productos</a></li>
	</ul>
	<div class="tab-content">
		<br>
		<div class="row">
      <div class="col-md-12">
        <table class="table">
          <tr>
            <td width="200px"><b>Nombre:</b></td>
            <td><%= @user.full_name %></td>
          </tr>
          <tr>
            <td width="200px"><b>Email:</b></td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td width="200px"><b>Rol:</b></td>
            <td><%= @user.role %></td>
          </tr>
          <tr>
            <td width="200px"><b>Estado:</b></td>
            <td><%= @user.status %></td>
          </tr>
          <tr>
            <td width="200px"><b>Fecha de creación:</b></td>
            <td><%= @user.created_at %></td>
          </tr>
        </table>
      </div>
		</div>
	</div>
</div>


<div id="row-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">

</div>

<% content_for :footer_scripts do  -%>

	<script type="text/javascript">

    function load_edit_user_form(){
      $.get("<%= edit_admin_user_path(@user) -%>", function(view){
				$("#row-modal").html(view)
				$("#row-modal").modal('show')
			})
    }

	</script>
<% end -%>