config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  namespace :admin do
    get '/' => 'home#index'
    resources :products do
      resources :tracks
    end
    resources :users do
      get 'products'
      get 'all_products'
      post 'assign_product'
      delete 'remove_product'
    end
  end

  apipie
  devise_for :users
	namespace :api do
		post 'login' => 'sessions#create'
    post 'register' => 'registrations#create'
    post 'forgot-password' => 'sessions#forgot_password'

    get 'products' => 'products#index'
    get 'tracks' => 'tracks#index'

    get 'track-detail' => 'tracks#show'
	end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>TrackManager</title>

  <meta name="description" content="">
  <meta name="author" content="Entropia">
  <meta name="robots" content="">

  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

  <%= stylesheet_link_tag    "backend/application", :media => "all" %>
  <%= javascript_include_tag "backend/application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <!-- Page Wrapper -->
  <div id="page-wrapper" class="page-loading">
    <!-- Preloader -->
    <div class="preloader themed-background">
      <h1 class="push-top-bottom text-light text-center"><%= image_tag "logo.png" %></h1>
      <div class="preloader-spinner hidden-lt-ie9 hidden-lt-ie10"></div>
      <div class="inner">
        <h3 class="text-light visible-lt-ie9 visible-lt-ie10"><strong>Cargando...</strong></h3>

      </div>
    </div>
    <!-- END Preloader -->

    <!-- Page Container -->
    <div id="page-container" class=" sidebar-visible-lg enable-cookies ">
      <!-- Alternative Sidebar -->
      <div id="sidebar-alt">
        <!-- Wrapper for scrolling functionality -->
        <div id="sidebar-alt-scroll">
          <!-- Sidebar Content -->
          <div class="sidebar-content">

            <!-- Activity -->
            <a href="javascript:void(0)" class="sidebar-title">
              <i class="fa fa-globe pull-right"></i> <strong>Notificaciones</strong>
            </a>
            <div class="sidebar-section">

            </div>
            <!-- END Activity -->

          </div>
          <!-- END Sidebar Content -->
        </div>
        <!-- END Wrapper for scrolling functionality -->
      </div>
      <!-- END Alternative Sidebar -->

      <!-- Main Sidebar -->
      <div id="sidebar">
        <!-- Wrapper for scrolling functionality -->
        <div id="sidebar-scroll">
          <!-- Sidebar Content -->
          <div class="sidebar-content">
            <!-- Brand -->
            <a href="/" class="sidebar-brand">
              <span class="sidebar-nav-mini-hide">Track Manager</span>
            </a>
            <!-- END Brand -->

            <!-- User Info -->
            <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
              <div class="sidebar-user-avatar">
                <a href="<%= root_path %>">
                  <%= image_tag "missing_user.jpg", :alt => "avatar" %>
                </a>
              </div>
              <div class="sidebar-user-name">Bienvenido</div>
              <div class="sidebar-user-links">
                <a href="<%= '/' %>" data-toggle="tooltip" data-placement="bottom" title="Perfil"><i class="gi gi-user"></i></a>
                <!-- Opens the user settings modal that can be found at the bottom of each page (page_footer.html in PHP version) -->
                <a href="javascript:void(0)" class="enable-tooltip" data-placement="bottom" title="Configuración" onclick="$('#modal-user-settings').modal('show');"><i class="gi gi-cogwheel"></i></a>
                <a href="<%= destroy_user_session_path %>" data-method="delete" data-toggle="tooltip" data-placement="bottom" title="Cerrar sesión"><i class="gi gi-exit"></i></a>
              </div>
            </div>
            <!-- END User Info -->

            <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
              <li class="<%= 'active' if controller_name == "home" %>">
                <a href="<%= admin_path %>"><i class="gi gi-home sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Inicio</span></a>
              </li>
              <li class="<%= 'active' if controller_name == 'products' or controller_name == 'tracks' %>">
                <a href="<%= admin_products_path %>"><i class="fa fa-music sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Productos</span></a>
              </li>
              <li class="<%= 'active' if controller_name == 'users' %>">
                <a href="<%= admin_users_path  %>"><i class="gi gi-group sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Usuarios</span></a>
              </li>
            </ul>
            <!-- END Sidebar Navigation -->

          </div>
          <!-- END Sidebar Content -->
        </div>
        <!-- END Wrapper for scrolling functionality -->
      </div>
      <!-- END Main Sidebar -->

      <!-- Main Container -->
      <div id="main-container">
        <!-- Header -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!--
        Available header.navbar classes:

        'navbar-default'            for the default light header
        'navbar-inverse'            for an alternative dark header

        'navbar-fixed-top'          for a top fixed header (fixed sidebars with scroll will be auto initialized, functionality can be found in js/app.js - handleSidebar())
        'header-fixed-top'      has to be added on #page-container only if the class 'navbar-fixed-top' was added

        'navbar-fixed-bottom'       for a bottom fixed header (fixed sidebars with scroll will be auto initialized, functionality can be found in js/app.js - handleSidebar()))
        'header-fixed-bottom'   has to be added on #page-container only if the class 'navbar-fixed-bottom' was added
      -->
      <header class="navbar navbar-default">
        <!-- Left Header Navigation -->
        <ul class="nav navbar-nav-custom">
          <!-- Main Sidebar Toggle Button -->
          <li>
            <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');this.blur();">
              <i class="fa fa-bars fa-fw"></i>
            </a>
          </li>
          <!-- END Main Sidebar Toggle Button -->
        </ul>
        <!-- END Left Header Navigation -->

        <!-- Right Header Navigation -->
        <ul class="nav navbar-nav-custom pull-right">
          <!-- Alternative Sidebar Toggle Button -->
          <li>
            <!-- If you do not want the main sidebar to open when the alternative sidebar is closed, just remove the second parameter: App.sidebar('toggle-sidebar-alt'); -->
            <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar-alt', 'toggle-other');this.blur();">
              <i class="gi gi-bell"></i>
              <span class="label label-primary label-indicator animation-floating"></span>
            </a>
          </li>
          <!-- END Alternative Sidebar Toggle Button -->

          <!-- User Dropdown -->
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag 'missing_user.jpg', :alt => "avatar" %> <i class="fa fa-angle-down"></i>

            </a>
            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
              <li>
                <a href="<%=  %>">
                  <i class="gi gi-user pull-right"></i>
                  Perfil
                </a>
                <!-- Opens the user settings modal that can be found at the bottom of each page (page_footer.html in PHP version) -->
                <a href="#modal-user-settings" data-toggle="modal">
                  <i class="gi gi-cogwheel pull-right"></i>
                  Configuración
                </a>
              </li>
              <li>
                <a href="<%= destroy_user_session_path %>" data-method="delete"><i class="gi gi-exit pull-right"></i> Cerrar sesión</a>
              </li>
            </ul>
          </li>
          <!-- END User Dropdown -->
        </ul>
        <!-- END Right Header Navigation -->
      </header>
      <!-- END Header -->

      <!-- Page content -->
      <div id="page-content">

        <%= yield %>

      </div>
      <!-- END Page Content -->

      <!-- Footer -->
      <footer class="clearfix">
        <div class="pull-right">
          Desarrollado con <i class="fa fa-heart"></i> por <a href="http://entropia.co" target="_blank">Entropía</a>
        </div>
      </footer>
      <!-- END Footer -->
    </div>
    <!-- END Main Container -->
  </div>
  <!-- END Page Container -->
</div>
<!-- END Page Wrapper -->

<!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
<a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>

<%= yield :footer_scripts %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="sp"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>TrackManager</title>

  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

  <%= stylesheet_link_tag    "frontend/application", :media => "all" %>
  <%= javascript_include_tag "frontend/application" %>
  <%= csrf_meta_tags %>

</head>

<body>

  <div id="page-container">
    <!-- Site Header -->
    <header>
      <div class="container">
        <!-- Site Logo -->
        <a href="/" class="site-logo" style="margin-top: -20px;">
          <%= image_tag "logo.png", :width => '75px' %>
        </a>
        <!-- Site Logo -->

        <!-- Site Navigation -->
        <nav>
          <!-- Menu Toggle -->
          <!-- Toggles menu on small screens -->
          <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm">
            <i class="fa fa-bars"></i>
          </a>
          <!-- END Menu Toggle -->

          <!-- Main Menu -->
          <ul class="site-nav">
            <!-- Toggles menu on small screens -->
            <li class="visible-xs visible-sm">
              <a href="javascript:void(0)" class="site-menu-toggle text-center">
                <i class="fa fa-times"></i>
              </a>
            </li>
            <!-- END Menu Toggle -->
            <li <%= "class=active" if action_name == "about" %>>
              <a href="<%= root_path %>">Inicio</a>
            </li>
            <li>
              <a href="<%= admin_path %>">Ingresar</a>
            </li>
          </ul>
          <!-- END Main Menu -->
        </nav>
        <!-- END Site Navigation -->
      </div>
    </header>
    <!-- END Site Header -->

    <%= yield %>

    <!-- Footer -->
    <footer class="site-footer site-section">
      <div class="container">
        <!-- Footer Links -->
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <h4 class="footer-heading">Acerca de nosotros</h4>
            <p>
              Somos una empresa dedicada a fabricar y comercializar productos y servicios para la salud de los animales.
              A través de la dieta BARF, queremos brindar las mejores opciones para la vida saludable de perros y gatos.
            </p>
            <ul class="footer-nav list-inline">
              <li><a href="/nosotros">Compañía</a></li>
              <li><a href="/contacto">Contacto</a></li>
              <li><a href="/politica-privacidad">Política de privacidad</a></li>
            </ul>
          </div>

          <div class="col-sm-6 col-md-4">
            <h4 class="footer-heading">Encuéntranos también en</h4>
            <ul class="footer-nav footer-nav-social list-inline">
              <li><a href="http://fb.com/Barffitmedellin" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a href="https://www.instagram.com/barffit.med/"><i class="fa fa-instagram"></i></a></li>
              <li><a href="/contacto"><i class="fa fa-envelope"></i></a></li>
              <!-- <li><a href="javascript:void(0)"><i class="fa fa-rss"></i></a></li> -->
            </ul>
            <div class="fb-page" data-href="https://www.facebook.com/Barffitmedellin/" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Barffitmedellin/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Barffitmedellin/">BarfFit</a></blockquote></div>
          </div>
          <div class="col-sm-6 col-md-4">
            <h4 class="footer-heading"><span id="year-copy">2016</span> &copy; <a href="http://barffit.co">BarfFit en Medellín</a></h4>
            <ul class="footer-nav list-inline">
              <li>Diseñado con <i class="fa fa-heart text-danger"></i> por <a target="_blank" href="http://entropia.co">Entropia.co</a></li>
            </ul>
            <p>
              Google Play y el logotipo de Google Play son marcas comerciales de Google Inc.
            </p>
            <p>
              <span id="siteseal"><script async type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=FfDjJcVcIBaI72kk1GY2E7YqrpPsHKt5zlQA55CeLlHvdRU7hCr9XTo0rs4H"></script></span>
            </p>
            <p>
              <a target="_blank" class="footer-app" href='https://play.google.com/store/apps/details?id=com.entropia.barffit&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'><img id="playstore-logo" alt='Disponible en Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/es-419_badge_web_generic.png'/></a>
            </p>
          </div>
        </div>
        <!-- END Footer Links -->
      </div>

    </footer>
    <!-- END Footer -->
  </div>
  <!-- END Page Container -->

  <a href="#" id="to-top"><i class="fa fa-angle-up"></i></a>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>ProUI - Responsive Bootstrap Admin Template</title>

  <%= stylesheet_link_tag    "backend/application", :media => "all" %>
  <%= javascript_include_tag "backend/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Login Background -->
  <div id="login-background">
    <!-- For best results use an image with a resolution of 2560x400 pixels (prefer a blurred image for smaller file size) -->
    <%= image_tag "login_header", class: 'animation-pulseSlow' %>
  </div>
  <!-- END Login Background -->

  <!-- Login Container -->
  <div id="login-container" class="animation-fadeIn">
    <!-- Login Title -->
    <div class="login-title text-center">
      <h1><i class="gi gi-flash"></i> <strong>ProUI</strong><br><small>Please <strong>Login</strong> or <strong>Register</strong></small></h1>
    </div>
    <!-- END Login Title -->

    <!-- Login Block -->
    <div class="block push-bit">
      <!-- Login Form -->
      <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'form-horizontal form-bordered form-control-borderless'}) do |f| %>
        <div class="form-group">
          <div class="col-xs-12">
            <div class="input-group">
              <span class="input-group-addon"><i class="gi gi-envelope"></i></span>
              <%= f.email_field :email, class:'form-control input-lg', placeholder: 'Email' %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <div class="input-group">
              <span class="input-group-addon"><i class="gi gi-asterisk"></i></span>
              <%= f.password_field :password, class:'form-control input-lg', placeholder: 'Password' %>
            </div>
          </div>
        </div>
        <div class="form-group form-actions">
          <div class="col-xs-8 text-right">
            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i> Login to Dashboard</button>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12 text-center">
            <a href="javascript:void(0)" id="link-reminder-login"><small>Olvidó su contraseña?</small></a>
          </div>
        </div>
      <% end %>
      <!-- END Login Form -->

      <!-- Reminder Form -->
      <form action="login.html#reminder" method="post" id="form-reminder" class="form-horizontal form-bordered form-control-borderless display-none">
        <div class="form-group">
          <div class="col-xs-12">
            <div class="input-group">
              <span class="input-group-addon"><i class="gi gi-envelope"></i></span>
              <input type="text" id="reminder-email" name="reminder-email" class="form-control input-lg" placeholder="Email">
            </div>
          </div>
        </div>
        <div class="form-group form-actions">
          <div class="col-xs-12 text-right">
            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-angle-right"></i> Reset Password</button>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-12 text-center">
            <small>Did you remember your password?</small> <a href="javascript:void(0)" id="link-reminder"><small>Login</small></a>
          </div>
        </div>
      </form>
      <!-- END Reminder Form -->

    </div>
    <!-- END Login Block -->

    <!-- Footer -->
    <footer class="text-muted text-center">
      <small><span id="year-copy"></span> &copy; <a href="https://1.envato.market/x4R" target="_blank">ProUI 3.8</a></small>
    </footer>
    <!-- END Footer -->
  </div>
  <!-- END Login Container -->

</body>
</html>